### ISSUE TITLE
Feature request: Width attribute for SearchComponent

### ISSUE THREAD

**Issue by ruoptic** [sbb-design-systems/sbb-angular#143]
*Problem*
At the moment there is `mode` attribute for text field which is used to define width of the field. For `SearchComponent` this attribute has a different meaning and there is no any other attribute to define width of search element.

*Suggestion*
It would be good to have a new attribute to set element width (e.g. like for text field):

````html
<sbb-search
          (search)="search()"
          [width]="long"
          placeholder="Suchen"
          [formControl]="searchField">
</sbb-search>
````

*Workaround*
At the moment to change element's width styles should be overridden:
````scss
.sbb-search {
  width: 100%;
  &::ng-deep>.sbb-search-box>input {
    width: calc(100% - 120px);
  }
}
````
