### ISSUE TITLE
Bug: Transparent background of UserMenu component

### ISSUE THREAD

**Issue by ruoptic** [sbb-design-systems/sbb-angular#164]
**Description**
When we add Header component with user menu inside we got a transparent background of UserMenu component. 

**To Reproduce**
Add a Header component from business components library.

**Screenshots**
![transparent-background](https://user-images.githubusercontent.com/2409938/64791101-e02b2e80-d57f-11e9-85b6-566674ba47f3.png)

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 76

**Workaround**
To fix this in global `styles.css` add code:
```css
.sbb-usermenu-logged-in-active {
  background-color: #fff;
}
```
