### ISSUE TITLE
Bug: Tabs don't display correctly for many/long tabs

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#943]
**Describe the bug**
When having many tabs (or long titles) - not all tabs are visible and it is not clear for the user that more tabs are available:
![image](https://user-images.githubusercontent.com/117919/144021964-78673c47-8127-4322-9544-d25c18d18625.png)

**Expected behavior**
Either follow the spec: https://digital.sbb.ch/de/webapps/components/tab where tabs should be shortened or apply some shadow/transparency at the end to make it visible to the user that more tabs are available by scrolling.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 13.rc2

**Additional context**
Probably a similiar behavior is needed for the process flow?

**Comment by daniel-sc** [comment]
The following CSS snippet probably would fix this (if developer setup was simpler, I'd provide an actual PR ;-) ):
```css
  .sbb-tabs-tablist-item {
    flex: 0 1 auto;
    min-width: 100px;
    .sbb-tabs-tablist-item-button {
      text-overflow: ellipsis;
      overflow: hidden;
    }
  }
```
